apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo
  labels:
    app: devsecops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-demo
  template:
    metadata:
      labels:
        app: devsecops-demo
    spec:
      containers:
      - name: devsecops-demo
        image: ghcr.io/suriya396/devsecops-demo:943f01466f7a42042e406a64f7962725cf72a849
        ports:
        - containerPort: 80
