apiVersion: v1
kind: Service
metadata:
  name: devsecops-demo-service
  labels:
    app: devsecops-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: devsecops-demo
